import "./globals.css"
import "react-toastify/dist/ReactToastify.css"
import "@rainbow-me/rainbowkit/styles.css"
import ToastProvider from "@/components/toast/ToastProvider"
import { CurrencyDataProvider } from "@/components/context/CurrencyContext"
import type { Metadata } from "next"
import { headers } from "next/headers"

// Wagmi
import { cookieToInitialState } from "wagmi"
import { config } from "./config/wagmi"
import Web3ModalProvider from "./config/web3"

import GlobalWrapper from "@/GlobalContext/GlobalWrapper"

// Next fonts
import { Inter } from "next/font/google"
import { ReactNode } from "react"

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600", "700"] })

type RootLayoutProps = {
  children: ReactNode
  session: any
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: RootLayoutProps) {
  const initialState = cookieToInitialState(config, headers().get("cookie"))
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col justify-between h-[100dvh]`}>
        <Web3ModalProvider initialState={initialState}>
          <ToastProvider>
            <CurrencyDataProvider>
              <GlobalWrapper>{children}</GlobalWrapper>
            </CurrencyDataProvider>
          </ToastProvider>
        </Web3ModalProvider>
      </body>
    </html>
  )
}
